server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: taifajnefajne
    key-alias: tomcat
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/db/tai_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect


iiet:
  client:
    clientId: 01296c56e93d9a9683bf07e174d20bc8f02fcf22f719b644c3d61d2ad89decc4
    clientSecret: 0eca5e82ecb2f0389cfaee612848d337d0cf031d175d9f25533dc1bcada5c9c0
    accessTokenUri: https://accounts.iiet.pl/oauth/token
    userAuthorizationUri: https://accounts.iiet.pl/oauth/authorize
    tokenName: oauth_token
    scope: public,extended
  require-ssl: true

  resource:
     userInfoUri: https://accounts.iiet.pl/oauth/v1/extended

